# Generated by Django 4.1.7 on 2023-05-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
