# Generated by Django 4.1.7 on 2023-05-18 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscribedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedusers',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='subscribedusers',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
