# Generated by Django 4.1.7 on 2023-05-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscribedusers_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedusers',
            name='user',
        ),
        migrations.AddField(
            model_name='subscribedusers',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
