# Generated by Django 4.1.7 on 2023-05-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_createed_at_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Picked by courier', 'Picked by courier'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='New', max_length=50),
        ),
    ]
