# Generated by Django 4.1.7 on 2023-05-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Picked by courier', 'Picked by courier'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Order Confirmed', max_length=50),
        ),
    ]
